name: build

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Check code format
        run: dotnet format --verify-no-changes KUPReportGenerator.sln
   
  release_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18

      - name: Install tools dependencies
        run: npm ci

      - name: Check next release version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACTIONS_TOKEN }}
        run: |
          npx semantic-release --no-ci --dry-run --debug

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            runtime: "win-x64"
          - os: ubuntu-latest
            runtime: "linux-x64"
          - os: macos-latest
            runtime: "osx-x64"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: |
          dotnet publish src/Installer/Installer.csproj -c Release -o ${{ env.DOTNET_ROOT }}/publish -r ${{ matrix.runtime }} -p:Version=1.0.0 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained=true
          dotnet publish src/KUPReportGenerator/KUPReportGenerator.csproj -c Release -o ${{ env.DOTNET_ROOT }}/publish -r ${{ matrix.runtime }} -p:Version=1.0.0 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained=true
