name: build

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Check Code Format
        run: dotnet format --verify-no-changes KUPReportGenerator.sln

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install tools dependencies
        run: npm ci

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Check next release version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACTIONS_TOKEN }}
        run: |
          npx semantic-release --no-ci --dry-run --debug
