name: version_release

on:
  push:
    branches: ["main"]

jobs:
  version-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: Install tools dependencies
        run: npm ci

      - name: Release version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACTIONS_TOKEN }}
        run: npx semantic-release
